site_name: Action Quality Assessment
site_url: https://triplepiers.github.io/AQA/
copyright: Copyright © 2023 SeaBee
plugins:
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
        - "%"
theme:
  name: material
  language: zh
  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/light-bulb-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.footer
    - navigation.expand
    - content.code.copy
    - content.code.annotate 
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - toc:
      toc_depth: 3
extra_css:
  # fonts
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
nav:
- Home: index.md
- Summary: sum.md
- Repitition: rep.md
- References:
  - 2021:
    - CoRe 组感知对比回归: ref/2021/CoRe.pdf
    - TSA-Net 管自注意力网络: ref/2021/TSA-Net.pdf
    - Video-based: ref/2021/Video-based.pdf
  - 2022:
    - TPA 时序转译 transformer: ref/2022/TPA.pdf
  - 2023:
    - PECoP 连续预训练: ref/2023/PECoP.pdf
    - FSPN 细粒度时空解析网络: ref/2023/STPN.pdf
    - IRIS 评分标准可解释分割: ref/2023/IRIS.pdf